services:
  stellaris-node:
    image: stellaris-node:latest
    container_name: stellaris-node
    tty: true
    restart: unless-stopped
    environment:
      - DATABASE_PATH=./data/database
      - NODE_HOST=0.0.0.0
      - NODE_PORT=5432
      - DEFAULT_NODES=https://stellaris-node.connor33341.dev
      - ENABLE_RATE_LIMITING=true
    ports:
      - "5432:5432"